# Generated by Django 2.2.7 on 2019-12-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
